### PR TITLE
Financial transactions fix

### LINKED ISSUE #392: Financial Transactions controller/view issues
- Filter function on the index page doesn't filter anything
- show view only has edit and back buttons
- edit form does not repopulate the fields
- edit has no corresponding update method in the controller

### PR DESCRIPTION
**Pull request by anmerkl**
closes #392 

Fixed filter on index page (though with a workaround)
Removed unneeded actions and views

### CODE REVIEW

File: app/controllers/financial_transactions_controller.rb [hunk 1]
```diff
@@ -1,63 +1,56 @@
 # frozen_string_literal: true
 class FinancialTransactionsController < ApplicationController
-  before_action :set_financial_transaction, only: [:show, :edit]
-
   after_action :set_return_url, only: [:index]
 
-  # GET /financial_transactions
   def index
-    @q = FinancialTransaction.search(params[:q])
+    # workaround for unknown Ransack bug
```
Comment (anmerkl) [inline app/controllers/financial_transactions_controller.rb]: The regular Ransack syntax `FinancialTransaction.search(params[:q])` was not working, which is why filter on the index page wasn't working.  For some reason, Ransack was not actually searching for anything as if `params[:q]` was `nil`.

File: config/routes.rb [hunk 2]
```diff
@@ -43,7 +41,7 @@
   resources :holds do
     post :lift, on: :member
   end
-  resources :financial_transaction, except: %i(destroy update)
```
Comment (anmerkl) [inline config/routes.rb]: I'm basing changes on this line as opposed to the above line because Metin said he did not want Financial Transactions to be deleted or edited after creation

File: app/controllers/financial_transactions_controller.rb [hunk 3]
```diff
@@ -23,41 +23,33 @@ def new
...
-  def edit; end
-
-  # POST /financial_transactions
   def create
     @financial_transaction = FinancialTransaction.new(financial_transaction_params)
     if @financial_transaction.transactable_type == Payment.name
-      payment = Payment.new(payment_params) # hard fail
+      payment = Payment.new(payment_params)
       unless payment.save
         flash[:danger] = 'Please Properly Fill Out Contact And Payment Fields'
```
Comment (Anbranin) [inline app/controllers/financial_transactions_controller.rb]: Would it be better to be clearer here, like so:
`flash[:danger] = payment.errors.full_messages`?
That is, if your application.html.erb is set up to accept flash[:danger] as an array.

Comment (Anbranin) [reply app/controllers/financial_transactions_controller.rb]: If that's outside of the scope of your PR, never mind--I just think it would be good to do.

File: app/controllers/financial_transactions_controller.rb [hunk 4]
```diff
@@ -23,41 +23,33 @@ def new
...
+        render :new and return
       end
+
       @financial_transaction.transactable_id = payment.id
     end
 
     if @financial_transaction.save
-      redirect_to rental_invoice_path(@financial_transaction.rental_id), success: 'Financial Transaction Successfully Created'
+      redirect_to rental_invoice_path(@financial_transaction.rental_id),
+                  success: 'Financial Transaction Successfully Created'
```
Comment (Anbranin) [inline app/controllers/financial_transactions_controller.rb]: Shouldn't this be in the flash?

File: app/controllers/financial_transactions_controller.rb (hunk 3 above)
Comment (anmerkl) [reply app/controllers/financial_transactions_controller.rb]: I agree, but I chose not to address that here because it will be addressed when I eventually finish #382

File: app/controllers/financial_transactions_controller.rb (hunk 1 above)
Comment (Cobchise) [reply app/controllers/financial_transactions_controller.rb]: Ransack usually doesn't return anything when params[:q] is nil, that's correct behavior as far as I can tell. Some people choose to apply their own filter when params[:q] is nil like below:
```
def index
  @search = Job.search(params[:q])
  @results = @search.result
  @results = @results.where(:your_date => nil) unless params[:q]
  @job = @results.paginate(:per_page => 10, :page => params[:page])
end
``` 
but I found a better example which actually changes the default return of the search object which may be a better approach:
```
def index
  @search = Job.search(params[:q])
  @search.status_cont = 'Open' unless params[:q]
  @results = @search.result
  @job = @results.paginate(:per_page => 10, :page => params[:page])
end
```
Hope this helps. Both of these can be seen [here](https://stackoverflow.com/questions/13284172/setting-default-search-parameter-on-ransack-for-rails)

File: spec/controllers/financial_transactions_controller_spec.rb [hunk 5]
```diff
@@ -138,22 +122,4 @@
...
-  describe 'PUT #update' do
-    it 'cannot find a route' do
-      ft = create :financial_transaction
-      expect do
-        put :update, params: { id: ft.to_param }
-      end.to raise_error AbstractController::ActionNotFound
-    end
-  end
-
-  describe 'DELETE #destroy' do
```
Comment (Cobchise) [inline spec/controllers/financial_transactions_controller_spec.rb]: I don't think you need to remove the destroy method as our permanent_records gem overrides the behavior. Instead of deleting the record when you call .destroy it adds a 'deleted_at' datetime column entry.

File: config/routes.rb (hunk 2 above)
Comment (Cobchise) [inline config/routes.rb]: Based again on the permanent_records gem I believe we can allow the destroy resource also, as permanent_records (as I noted below) overrides the destroy behavior

File: app/controllers/financial_transactions_controller.rb (hunk 1 above)
Comment (anmerkl) [reply app/controllers/financial_transactions_controller.rb]: The issue here was not that `params[:q]` was nil.  It was behaving as though `params[:q]` was nil.
If `params[:q]` is nil, Ransack doesn't do any filtering so it returns everything, which is why the filter function on the index page wasn't working.

File: app/controllers/financial_transactions_controller.rb (hunk 4 above)
Comment (anmerkl) [reply app/controllers/financial_transactions_controller.rb]: Yes, that will also be addressed in #382

File: spec/controllers/financial_transactions_controller_spec.rb (hunk 5 above)
Comment (anmerkl) [reply spec/controllers/financial_transactions_controller_spec.rb]: We actually never had a destroy method so I figured we didn't want it in the first place.

Comment (Cobchise) [reply spec/controllers/financial_transactions_controller_spec.rb]: Apologies, yep you're correct to remove this if the method it is testing doesn't exist... but it just begs the question why was it here at all? I'm still wondering why we don't have a destroy method for financial transactions

Comment (anmerkl) [reply spec/controllers/financial_transactions_controller_spec.rb]: I'd like to think this ended up here after a bunch of copy-pasting + making relevant edits to make the tests pass

We don't delete Financial Transactions because we'd like to keep track of everything related to money so it doesn't make sense to just delete these records.  We could consider adding a functionality to 'deactivate' Financial Transactions, but I don't think that that adds any useful functionality.

File: app/controllers/financial_transactions_controller.rb (hunk 1 above)
Comment (anmerkl) [reply app/controllers/financial_transactions_controller.rb]: Also, 
```
if params[:q]
  FinancialTransaction.search(transactable_type_eq: params[:q][:transactable_type])
...
```
looks to be logically equivalent to what this snippet is accomplishing
```
@results = @search.result
@results = @results.where(:your_date => nil) unless params[:q]
```
So there shouldn't be a problem.

File: spec/controllers/financial_transactions_controller_spec.rb (hunk 5 above)
Comment (Cobchise) [reply spec/controllers/financial_transactions_controller_spec.rb]: Well that was my point above, we already have permanent_records implemented so if we made a destroy method they wouldn't be deleted as permanent_records overrides that functionality. Making a destroy method would be effectively making a 'deactivate' method.

File: app/controllers/financial_transactions_controller.rb (hunk 1 above)
Comment (Cobchise) [reply app/controllers/financial_transactions_controller.rb]: It largely is, but I suggested it an an improvement because it doesn't require a weird else statement where you pass `nil` to FinancialTransaction.search

File: spec/controllers/financial_transactions_controller_spec.rb (hunk 5 above)
Comment (anmerkl) [reply spec/controllers/financial_transactions_controller_spec.rb]: I see.
I'd rather put that in a new issue and pull request then, based on what I read from the permanent_records documentation.  I think what is currently in this pull request is enough for the MVP. What do you think?

Comment (Cobchise) [reply spec/controllers/financial_transactions_controller_spec.rb]: Agreed. I'll make the issue now

File: app/controllers/financial_transactions_controller.rb (hunk 1 above)
Comment (anmerkl) [reply app/controllers/financial_transactions_controller.rb]: What do you think about the below implementation? It's a bit more complicated but is a lot cleaner

Comment (Cobchise) [reply app/controllers/financial_transactions_controller.rb]: Nice code man, I like that a lot. Thanks for changing it :+1: As long as it works then lgtm
