### PR TITLE
Refactor Inline styles and fixed disclaimer toggle

### LINKED ISSUE #120: Refactor inline styles
RE this conversation: https://github.com/umts/probable-engine/pull/118/files#r72454851

Please refactor the inline `display: none; etc...` style(s) by moving the formatting to the rental or global SASS/CSS file. A short investigation to clean up any additional inline styles would deal with this issue forever.

### PR DESCRIPTION
**Pull request by Cobchise**
### Closes #120 ###

Refactored inline styles from rental form to rental_schedule.css and added javascript to allow disclaimer to toggle correctly

### CODE REVIEW

File: app/assets/javascripts/global.js [hunk 1]
```diff
@@ -39,6 +39,14 @@ function toggle_loading(){
   $('#loading').toggle();
 }
 
+//Toggle disclaimers on rental schedule page
+function display_disc(select) {
+  for (i=0; i<=2; i++)
```
Comment (phantompatrol) [inline app/assets/javascripts/global.js]: Try: https://api.jquery.com/each/

Comment (Cobchise) [inline app/assets/javascripts/global.js]: Ah! Thank you! Writing that loop caused some horrible java flashbacks.... euguh

File: app/views/rentals/_form.html.erb [hunk 2]
```diff
@@ -77,7 +76,7 @@
       <div class="form-group col-xs-12">
         <%= f.label :type, 'Cart Type', class: 'control-label col-xs-2' %>
         <div class="col-xs-6">
-          <%= f.select :item_type_id, options_from_collection_for_select(@item_types, "id", "name"), {}, class: "selectpicker form-control" %>
+          <%= f.select :item_type_id, options_from_collection_for_select(@item_types, "id", "name"), {}, class: "selectpicker form-control", onchange: "display_disc(this)" %>
```
Comment (phantompatrol) [inline app/views/rentals/_form.html.erb]: Rather than invoking this directly, register a listener.

I did not realize @owlee had declared the on change event from the ruby. Rather, you can do it within the JS with something like:

```Javascript
$( document ).ready(function() {
  $('input[type=whatever]').click/change/etc(function( {$(this).closest...
```

That way, all form element that change the cart type can use the same piece of JS, and you won't have any need for `, onchange: "display_disc(this)"`

File: app/assets/javascripts/global.js [hunk 3]
```diff
@@ -28,6 +28,15 @@ $(document).ready(function() {
...
     });
+
+    //Adds listeners to select inputs to toggle disclaimers on rental schedule page
+    $(document.getElementsByName("rental[item_type_id]")).each(function() {
+      $(this).change(function () {
+        $(this).closest("form").find(".disclaimer").each(function() {
+          $(this).toggleClass("disclaimer-hidden")
+        })
+      })
+    })
```
Comment (phantompatrol) [inline app/assets/javascripts/global.js]: slow_clap_citizen_kane

Comment (phantompatrol) [inline app/assets/javascripts/global.js]: Actually, you may be able to do `closest("disclaimer")`

Comment (phantompatrol) [inline app/assets/javascripts/global.js]: Also, I have to ask, does selecting the same option again trigger this change?

Comment (Cobchise) [inline app/assets/javascripts/global.js]: @phantompatrol Hm, I tried a few different methods with closest("disclaimer") but it doesn't seem to return anything. I could look into that further? And no, selecting the same option again doesn't trigger the change 😃  On a sidenote I'm not sure why the travis build failed..
And aw the gif is gone 😢

Comment (phantompatrol) [inline app/assets/javascripts/global.js]: Oh, it will be back. I just wanted to confirm before reposting it. Naw, it is cool. Keep it this way and listen for the slow clap:

slow_clap_citizen_kane

Comment (phantompatrol) [inline app/assets/javascripts/global.js]: And @Cobchise would you might pushing a merge or a minor commit to the readme? I am thinking travis had a hiccup.
