### PR TITLE
Rental reservation event

### LINKED ISSUE #308: move rental.create_reservation to before save event
image
Doing it like this can cause an error when one is successful but the other fails

### PR DESCRIPTION
**Pull request by tomecho**
fixes #308

### CODE REVIEW

File: app/models/rental.rb [hunk 1]
```diff
@@ -88,14 +90,16 @@ def renter_is_assignable
...
     begin
       reservation = Inventory.create_reservation(item_type.name, start_time, end_time)
+      raise 'Reservation UUID was not present in response.' unless reservation[:uuid].present?
+
       self.reservation_id = reservation[:uuid]
       self.item = Item.find_by(name: reservation[:item][:name])
     rescue => error
       errors.add :base, error.inspect
-      return false
+      throw :abort
```
Comment (tomecho) [inline app/models/rental.rb]: welcome to the rails5 way of aborting `before_*`

File: app/models/rental.rb [hunk 2]
```diff
@@ -167,14 +171,6 @@ def duration
     (end_time.to_date - start_time.to_date).to_i + 1
   end
 
-  # this method seems really inefficient
-  # def self.with_balance_due
-  # Rental.select { |x| x.balance > 0 }
-  # end
-
-  # private
-  attr_accessor :skip_reservation_validation
```
Comment (tomecho) [inline app/models/rental.rb]: unless i am mistaken this isnt used

File: spec/models/rental_spec.rb [hunk 3]
```diff
@@ -345,22 +352,6 @@
     end
   end
 
-  describe '#create_reservation' do
```
Comment (tomecho) [inline spec/models/rental_spec.rb]: shouldn't call this method directly, it is a before_save event now.
